import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#030303] text-white/80 font-sans p-6 md:p-12 selection:bg-white selection:text-black">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-white/50 hover:text-white mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
        
        <h1 className="text-3xl md:text-4xl font-semibold text-white mb-8">Terms of Service</h1>
        <p className="mb-4 text-white/50">Last updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-invert prose-white max-w-none space-y-6">
          <section>
            <h2 className="text-xl text-white font-medium mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using Highwatch RAG (the "Service"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl text-white font-medium mb-3">2. Description of Service</h2>
            <p>
              Highwatch RAG is an AI-powered application that integrates with your Google Drive. The Service reads your documents (such as PDFs and Text files), extracts the text, creates vector embeddings, and uses a Large Language Model (LLM) to answer questions based on the content of your documents.
            </p>
          </section>

          <section>
            <h2 className="text-xl text-white font-medium mb-3">3. Use of Google Drive</h2>
            <p>
              By authenticating with Google OAuth, you grant the Service read-only permission to access your Google Drive files. You are solely responsible for ensuring that you have the legal right and authority to process, analyze, and upload the documents in your Google Drive. Do not use the Service to process highly sensitive, classified, or legally protected material if you are not authorized to do so.
            </p>
          </section>

          <section>
            <h2 className="text-xl text-white font-medium mb-3">4. AI Limitations and Liability</h2>
            <p>
              The Service uses artificial intelligence (LLaMA 3.3) to generate answers based on your documents. While the Service strives for accuracy:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li><strong>Hallucinations:</strong> The AI may occasionally produce incorrect, misleading, or fabricated information ("hallucinations").</li>
              <li><strong>Verification:</strong> You agree to independently verify all information generated by the Service before relying on it for critical decisions.</li>
              <li><strong>No Liability:</strong> We are not liable for any damages, losses, or negative consequences resulting from your reliance on the AI-generated output.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl text-white font-medium mb-3">5. User Conduct</h2>
            <p>
              You agree not to use the Service:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>In any way that violates any applicable national or international law or regulation.</li>
              <li>To process illegal, explicit, or highly abusive content.</li>
              <li>To attempt to hack, overload, or disrupt the Service's infrastructure or the third-party APIs (Groq, Google Drive, MongoDB) it relies upon.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl text-white font-medium mb-3">6. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl text-white font-medium mb-3">7. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}